window.CRANE_COMMENTS = {
  enabled: true,
  provider: "giscus",
  repo: "qqqzj-crane/qqqzj-crane-blog-assets",
  repoId: "R_kgDOSO9xPg",
  category: "Announcements",
  categoryId: "DIC_kwDOSO9xPs4C772p",
  mapping: "specific",
  strict: "1",
  reactionsEnabled: "1",
  emitMetadata: "0",
  inputPosition: "bottom",
  lang: "zh-CN",
  loading: "lazy",
  themeLight: "https://qqqzj.cn/giscus-light.css",
  themeDark: "https://qqqzj.cn/giscus-dark.css",
};
