window.PUBLISHED_POSTS = {
  "growth": [
    {
      "id": "news/2026-04-25-homepage-reading-polish.md",
      "slug": "2026-04-25-homepage-reading-polish",
      "dataPath": "post-data/2026-04-25-homepage-reading-polish.json",
      "source": "post",
      "kind": "growth",
      "title": "首页和阅读体验继续打磨",
      "publishedIndex": 0,
      "stage": "Site Update",
      "tag": "建站",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "今天继续把 qqqzj@Crane 的首页和阅读体验往更顺手的方向调整了一版。重点不是增加大功能，而是处理那些一打开页面就能感受到的细节：位置、层级、宽度、字号和交互是否舒服。 首页更像入口了 首页现在会展示最近几篇文章，读者不用先在各个栏...",
      "readingMinutes": 2,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-25-site-update-roundup.md",
      "slug": "2026-04-25-site-update-roundup",
      "dataPath": "post-data/2026-04-25-site-update-roundup.json",
      "source": "post",
      "kind": "growth",
      "title": "网站阶段更新：从内容归档到阅读体验",
      "publishedIndex": 1,
      "stage": "Site Update",
      "tag": "建站",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "这两天 qqqzj@Crane 做了一轮比较密集的维护，已经不只是“能放文章”的第一版了。现在它更像一个可以长期写、长期查、长期扩展的个人学习档案。 这次主要更新有几块。 内容和发布方式 网站现在采用 private 源码仓库和 publi...",
      "readingMinutes": 2,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-24-first-news.md",
      "slug": "2026-04-24-first-news",
      "dataPath": "post-data/2026-04-24-first-news.json",
      "source": "post",
      "kind": "growth",
      "title": "完成个人网站第一版",
      "publishedIndex": 2,
      "stage": "Project 项目",
      "tag": "建站",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "今天借助 Codex 把 qqqzj@Crane 的第一版搭起来了，感谢 Chatgpt 呜呜呜。",
      "readingMinutes": 1,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-27-实现app.md",
      "slug": "2026-04-27-实现app",
      "dataPath": "post-data/2026-04-27-%E5%AE%9E%E7%8E%B0app.json",
      "source": "post",
      "kind": "growth",
      "title": "实现app",
      "publishedIndex": 13,
      "stage": "News 动态",
      "tag": "随笔",
      "author": "Trae645",
      "url": "",
      "previewImage": {
        "src": "https://github.com/qqqzj-crane/qqqzj-crane-blog-assets/releases/download/assets-news-2026-04-27-%E5%AE%9E%E7%8E%B0app/IMG_8988.jpg",
        "alt": "IMG_8988"
      },
      "excerpt": "ai王朝了我说",
      "readingMinutes": 1,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-27-site-app-performance-update.md",
      "slug": "2026-04-27-site-app-performance-update",
      "dataPath": "post-data/2026-04-27-site-app-performance-update.json",
      "source": "post",
      "kind": "growth",
      "title": "网站 App 化和阅读性能继续打磨",
      "publishedIndex": 14,
      "stage": "Site Update",
      "tag": "建站",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "这两天 qqqzj@Crane 又往前推了一截。对访客来说，它现在更像一个可以长期打开、长期阅读、长期回看的个人站：入口更清楚，页面更轻，文章和附件也更适合在手机和电脑上慢慢看。 这一轮更新主要集中在几个前台体验上。 域名和 App 化 主...",
      "readingMinutes": 2,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-27-public-site-feature-guide.md",
      "slug": "2026-04-27-public-site-feature-guide",
      "dataPath": "post-data/2026-04-27-public-site-feature-guide.json",
      "source": "post",
      "kind": "growth",
      "title": "现在前台能用什么：一份访客功能说明",
      "publishedIndex": 15,
      "stage": "Site Guide",
      "tag": "建站",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "趁着这一轮更新刚收好，把 qqqzj@Crane 的前台也整理成一份说明。这里说的前台，就是普通访客打开 qqqzj.cn 后能直接看到、能直接使用的部分。 现在这个站点不只是文章列表，它更像一个小型个人档案馆：可以按时间看动态，按主题读笔...",
      "readingMinutes": 3,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-28-重大决策.md",
      "slug": "2026-04-28-重大决策",
      "dataPath": "post-data/2026-04-28-%E9%87%8D%E5%A4%A7%E5%86%B3%E7%AD%96.json",
      "source": "post",
      "kind": "growth",
      "title": "重大决策！",
      "publishedIndex": 20,
      "stage": "News 动态",
      "tag": "更新",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "我决定将我的github用户名从 ZijunQiu-a改成qqqzj-crane！！！",
      "readingMinutes": 1,
      "createdAt": "2026-04-28T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-29-重磅上线评论功能.md",
      "slug": "2026-04-29-重磅上线评论功能",
      "dataPath": "post-data/2026-04-29-%E9%87%8D%E7%A3%85%E4%B8%8A%E7%BA%BF%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD.json",
      "source": "post",
      "kind": "growth",
      "title": "重磅上线评论功能！！！",
      "publishedIndex": 24,
      "stage": "News 动态",
      "tag": "网站",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "::: warning 本文由Chatgpt 5.5创作 ::: 4 月 29 日 天气 不知道，反正我还在和代码搏斗 重磅上线评论功能！！！ 虽然这个标题看起来很像什么震惊部，但是请允许我稍微震惊一下。毕竟这个网站从一开始的一片荒地，到现...",
      "readingMinutes": 2,
      "createdAt": "2026-04-29T00:00:00.000Z"
    }
  ],
  "notes": [
    {
      "id": "notes/physics/2026-04-24-physics-lab-markdown-template.md",
      "slug": "2026-04-24-physics-lab-markdown-template",
      "dataPath": "post-data/2026-04-24-physics-lab-markdown-template.json",
      "source": "post",
      "kind": "notes",
      "title": "普物实验docx模版(❌)markdown(☑️)",
      "publishedIndex": 4,
      "stage": "Notes 笔记",
      "tag": "普物实验",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "我弄了这个 Markdown 模版，之后写普物实验报告就不用再被 docx 格式卡住了。 文件放在这里，直接下载就能用。 下载实验报告 Markdown 模版 下载预习报告 Markdown 模版 下载配套 CSS 样式",
      "readingMinutes": 1,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-24-mathematical-analysis-i.md",
      "slug": "2026-04-24-mathematical-analysis-i",
      "dataPath": "post-data/2026-04-24-mathematical-analysis-i.json",
      "source": "post",
      "kind": "notes",
      "title": "数学分析 I",
      "publishedIndex": 5,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "实数、确界与函数 实数集的基本性质 实数集 $\\mathbb R$ 的常用性质： 1. 有序性：任意 $a,b\\in\\mathbb R$ 可比较大小。 2. 传递性：若 $ab$，$bc$，则 $ac$。 3. 阿基米德性：若 $a0$，$...",
      "readingMinutes": 22,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-24-mathematical-analysis-i-review-outline.md",
      "slug": "2026-04-24-mathematical-analysis-i-review-outline",
      "dataPath": "post-data/2026-04-24-mathematical-analysis-i-review-outline.json",
      "source": "post",
      "kind": "notes",
      "title": "数学分析 I 复习提纲",
      "publishedIndex": 6,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "来源：数分I复习.pdf。 参考校订：数学分析 上.pdf、《数学分析》辅导.pdf。 本文件按复习页内容整理为考前提纲，公式已按标准表述校正。 1. 实数完备性与确界 确界原理 非空有上界数集必有上确界；非空有下界数集必有下确界。 等价完...",
      "readingMinutes": 5,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-24-linear-algebra-i.md",
      "slug": "2026-04-24-linear-algebra-i",
      "dataPath": "post-data/2026-04-24-linear-algebra-i.json",
      "source": "post",
      "kind": "notes",
      "title": "线性代数 I",
      "publishedIndex": 7,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "线性方程组与行简化阶梯形 行简化阶梯形 行简化阶梯矩阵满足： 1. 零行在非零行下方； 2. 每个非零行首个非零元为 $1$； 3. 主元所在列其余元素全为 $0$； 4. 主元位置从上到下向右移动。 线性方程组化为简化阶梯形后： 出现 $...",
      "readingMinutes": 19,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/physics/2026-04-25-physics-i-midterm-review-outline.md",
      "slug": "2026-04-25-physics-i-midterm-review-outline",
      "dataPath": "post-data/2026-04-25-physics-i-midterm-review-outline.json",
      "source": "post",
      "kind": "notes",
      "title": "普物 I 期中复习提纲（重点速览版）",
      "publishedIndex": 8,
      "stage": "Notes 笔记",
      "tag": "普物 I",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "General Physics I Midterm Review Outline / 普物 I 期中复习提纲 Based on / 依据：slides 课件、homework 作业、midterm 历年期中卷。 Focus / 重点：mec...",
      "readingMinutes": 9,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "notes/physics/2026-04-25-physics-i-midterm-mechanics-complete-review.md",
      "slug": "2026-04-25-physics-i-midterm-mechanics-complete-review",
      "dataPath": "post-data/2026-04-25-physics-i-midterm-mechanics-complete-review.json",
      "source": "post",
      "kind": "notes",
      "title": "普物 I 期中复习提纲（力学全覆盖版）",
      "publishedIndex": 9,
      "stage": "Notes 笔记",
      "tag": "普物 I",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "General Physics I Midterm Review Outline / 普物 I 期中复习提纲（Mechanics 讲义全覆盖版） Main reference / 主参考：普物I/reference books/mechan...",
      "readingMinutes": 14,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-28-离散数学笔记.md",
      "slug": "2026-04-28-离散数学笔记",
      "dataPath": "post-data/2026-04-28-%E7%A6%BB%E6%95%A3%E6%95%B0%E5%AD%A6%E7%AC%94%E8%AE%B0.json",
      "source": "post",
      "kind": "notes",
      "title": "离散数学笔记",
      "publishedIndex": 21,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "离散数学课堂笔记/ Discrete Mathematics Notes 参考资料 / Main references: MIT 6.042J / 6.1200J Mathematics for Computer Science, Rose...",
      "readingMinutes": 68,
      "createdAt": "2026-04-28T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-29-linear-algebra-ii-notes.md",
      "slug": "2026-04-29-linear-algebra-ii-notes",
      "dataPath": "post-data/2026-04-29-linear-algebra-ii-notes.json",
      "source": "post",
      "kind": "notes",
      "title": "Linear algebra II notes",
      "publishedIndex": 23,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "按《线性代数应该这样学》第四版中文版目录编排。 本笔记是学习整理版：每节按“定义与对象 → 定理与证明 → 例题”组织，证明尽量保留核心逻辑，便于复习时快速还原完整证明。 下载完整 PDF 笔记 --- 第 1 章 向量空间 1A $\\ma...",
      "readingMinutes": 42,
      "createdAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-29-线性代数ii-第七章笔记.md",
      "slug": "2026-04-29-线性代数ii-第七章笔记",
      "dataPath": "post-data/2026-04-29-%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0ii-%E7%AC%AC%E4%B8%83%E7%AB%A0%E7%AC%94%E8%AE%B0.json",
      "source": "post",
      "kind": "notes",
      "title": "线性代数II 第七章笔记",
      "publishedIndex": 25,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "第 7 章 内积空间上的算子 本章默认 $V,W,U$ 都是有限维内积空间，标量域 $F$ 为 $\\mathbb R$ 或 $\\mathbb C$。内积按本书约定对第一个变量线性、对第二个变量共轭线性： $$ \\langle \\lambda...",
      "readingMinutes": 27,
      "createdAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-29-离散数学计数原理笔记.md",
      "slug": "2026-04-29-离散数学计数原理笔记",
      "dataPath": "post-data/2026-04-29-%E7%A6%BB%E6%95%A3%E6%95%B0%E5%AD%A6%E8%AE%A1%E6%95%B0%E5%8E%9F%E7%90%86%E7%AC%94%E8%AE%B0.json",
      "source": "post",
      "kind": "notes",
      "title": "离散数学计数原理笔记",
      "publishedIndex": 26,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "计数原理专题笔记 / Counting Principles Notes 主线说明 / Main line: 本笔记按离散数学教材常见顺序整理计数原理：有限集合基数规则、基本计数法、排列组合、二项式与多项式、容斥、鸽巢、星棒法、多重集合、错...",
      "readingMinutes": 19,
      "createdAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "notes/programming/2026-04-29-datastructure-tree.md",
      "slug": "2026-04-29-datastructure-tree",
      "dataPath": "post-data/2026-04-29-datastructure-tree.json",
      "source": "post",
      "kind": "notes",
      "title": "DataStructure_Tree",
      "publishedIndex": 27,
      "stage": "Notes 笔记",
      "tag": "programming",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "树专题复习笔记 0. 总览 树专题在这门课里大致分成四块： 1. 普通树与二叉树：术语、表示法、遍历、表达式树、线索二叉树。 2. 二叉搜索树 BST：ADT、查找、插入、删除、平均情况分析。 3. 优先队列与二叉堆：堆的结构性质、堆序性质...",
      "readingMinutes": 10,
      "createdAt": "2026-04-29T00:00:00.000Z"
    },
    {
      "id": "notes/programming/2026-05-03-algorithm-list-stack-queue-复习笔记.md",
      "slug": "2026-05-03-algorithm-list-stack-queue-复习笔记",
      "dataPath": "post-data/2026-05-03-algorithm-list-stack-queue-%E5%A4%8D%E4%B9%A0%E7%AC%94%E8%AE%B0.json",
      "source": "post",
      "kind": "notes",
      "title": "Algorithm / List / Stack / Queue 复习笔记",
      "publishedIndex": 29,
      "stage": "Notes 笔记",
      "tag": "programming",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "Algorithm / List / Stack / Queue 复习笔记 0. 总览 这份笔记把以下四块按课程学习顺序整理成一份连续笔记： 1. Algorithm Analysis：算法定义、复杂度、渐进记号、循环/递归分析、最大子列和...",
      "readingMinutes": 19,
      "createdAt": "2026-05-03T00:00:00.000Z"
    },
    {
      "id": "notes/programming/2026-05-03-graph.md",
      "slug": "2026-05-03-graph",
      "dataPath": "post-data/2026-05-03-graph.json",
      "source": "post",
      "kind": "notes",
      "title": "Graph",
      "publishedIndex": 30,
      "stage": "Notes 笔记",
      "tag": "programming",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "图专题复习笔记 0. 总览 图专题在这门课里主要按以下顺序展开： 1. Graph definitions：图、无向图、有向图、路径、连通性、度、DAG。 2. Representation of graphs：邻接矩阵、邻接表、逆邻接表、...",
      "readingMinutes": 10,
      "createdAt": "2026-05-03T00:00:00.000Z"
    }
  ],
  "videos": [
    {
      "id": "life/2026-04-24-04-travel-jinan&taishan.md",
      "slug": "2026-04-24-04-travel-jinan-taishan",
      "dataPath": "post-data/2026-04-24-04-travel-jinan-taishan.json",
      "source": "post",
      "kind": "videos",
      "title": "清明de济南与泰山",
      "publishedIndex": 3,
      "stage": "Project 项目",
      "tag": "旅游",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": {
        "src": "https://github.com/qqqzj-crane/qqqzj-crane-blog-assets/releases/download/assets-2026-04-24-travel-jinan-taishan/baotuquan.jpeg",
        "alt": "趵突泉"
      },
      "excerpt": "为了这次出行，清明前我真的付出了太多～～ 趵突泉 竟然只是三个冒水的洞？！ 夜里的泰山 泰山日出 “日上，正赤如丹，下有红光动摇承之”",
      "readingMinutes": 1,
      "createdAt": "2026-04-04T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-25-真好-又浪费了一天.md",
      "slug": "2026-04-25-真好-又浪费了一天",
      "dataPath": "post-data/2026-04-25-%E7%9C%9F%E5%A5%BD-%E5%8F%88%E6%B5%AA%E8%B4%B9%E4%BA%86%E4%B8%80%E5%A4%A9.json",
      "source": "post",
      "kind": "videos",
      "title": "真好，又浪费了一天",
      "publishedIndex": 10,
      "stage": "Life 生活",
      "tag": "日常",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "我真服了 今天的 Chatgpt 让我很恼火，今天的 General Physics 更是火上浇油 一边复习，一边对着电脑和他互动。不仅复习不成，功能也没给我正确实现（我已急哭） 好在最后也是成功优化了 UI 界面，不过下周三要考普物期中了...",
      "readingMinutes": 1,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-26-这个后端推送给我弄死了.md",
      "slug": "2026-04-26-这个后端推送给我弄死了",
      "dataPath": "post-data/2026-04-26-%E8%BF%99%E4%B8%AA%E5%90%8E%E7%AB%AF%E6%8E%A8%E9%80%81%E7%BB%99%E6%88%91%E5%BC%84%E6%AD%BB%E4%BA%86.json",
      "source": "post",
      "kind": "videos",
      "title": "这个后台推送给我弄死了",
      "publishedIndex": 11,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "我真花了一早上 现在午饭还没吃 又玩了一早上AI 两点了还没吃",
      "readingMinutes": 1,
      "createdAt": "2026-04-26T00:00:00.000Z"
    },
    {
      "id": "notes/随笔/2026-04-26-qzj-老爹莅临检查.md",
      "slug": "2026-04-26-qzj-老爹莅临检查",
      "dataPath": "post-data/2026-04-26-qzj-%E8%80%81%E7%88%B9%E8%8E%85%E4%B8%B4%E6%A3%80%E6%9F%A5.json",
      "source": "post",
      "kind": "videos",
      "title": "qzj 老爹（并非）莅临检查",
      "publishedIndex": 12,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "junchao353-glitch",
      "url": "",
      "previewImage": {
        "src": "https://github.com/qqqzj-crane/qqqzj-crane-blog-assets/releases/download/assets-notes-%E9%9A%8F%E7%AC%94-2026-04-26-qzj-%E8%80%81%E7%88%B9%E8%8E%85%E4%B8%B4%E6%A3%80%E6%9F%A5/IMG_8415.jpg",
        "alt": "ljc我是你爸爸"
      },
      "excerpt": "加油吧撑过这段时间就好了宝宝",
      "readingMinutes": 1,
      "createdAt": "2026-04-26T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-27-实验室好累.md",
      "slug": "2026-04-27-实验室好累",
      "dataPath": "post-data/2026-04-27-%E5%AE%9E%E9%AA%8C%E5%AE%A4%E5%A5%BD%E7%B4%AF.json",
      "source": "post",
      "kind": "videos",
      "title": "实验室好累",
      "publishedIndex": 16,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "Trae645",
      "url": "",
      "previewImage": {
        "src": "https://github.com/qqqzj-crane/qqqzj-crane-blog-assets/releases/download/assets-drafts-draft-2026-04-27-mogw92dy-d7548828/1ddc629b5dc3d09b77765b440753fbd8.png",
        "alt": "没救了"
      },
      "excerpt": "严肃品鉴unitree代码中",
      "readingMinutes": 1,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-27-我最近好像有点幸福了.md",
      "slug": "2026-04-27-我最近好像有点幸福了",
      "dataPath": "post-data/2026-04-27-%E6%88%91%E6%9C%80%E8%BF%91%E5%A5%BD%E5%83%8F%E6%9C%89%E7%82%B9%E5%B9%B8%E7%A6%8F%E4%BA%86.json",
      "source": "post",
      "kind": "videos",
      "title": "我最近好像有点幸福了",
      "publishedIndex": 17,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "junchao353-glitch",
      "url": "",
      "previewImage": null,
      "excerpt": "我好像天快晴了",
      "readingMinutes": 1,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-27-也许这是成长的必经之路吧.md",
      "slug": "2026-04-27-也许这是成长的必经之路吧",
      "dataPath": "post-data/2026-04-27-%E4%B9%9F%E8%AE%B8%E8%BF%99%E6%98%AF%E6%88%90%E9%95%BF%E7%9A%84%E5%BF%85%E7%BB%8F%E4%B9%8B%E8%B7%AF%E5%90%A7.json",
      "source": "post",
      "kind": "videos",
      "title": "也许这是成长的必经之路吧",
      "publishedIndex": 18,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "4 月 27 日 天气 晴 复习了一个周末的普物终究是有了点起色，但是维护这个网站又耗费了我太多气力，尽管看着它一点点壮大，也有越来越多文字，心中不免涌上自豪之感，可这并不能冲淡我对人生的迷茫。或许不只是学业上。 诚然 LLM 与 Agen...",
      "readingMinutes": 1,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-28-恍若昨日-恍若隔世.md",
      "slug": "2026-04-28-恍若昨日-恍若隔世",
      "dataPath": "post-data/2026-04-28-%E6%81%8D%E8%8B%A5%E6%98%A8%E6%97%A5-%E6%81%8D%E8%8B%A5%E9%9A%94%E4%B8%96.json",
      "source": "post",
      "kind": "videos",
      "title": "恍若昨日 恍若隔世",
      "publishedIndex": 19,
      "stage": "Life Log 生活记录",
      "tag": "钢琴",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "我要卖掉我的房子 浪迹天涯 @bilibili:弹唱",
      "readingMinutes": 1,
      "createdAt": "2026-04-28T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-28-我迷失在了黑夜里.md",
      "slug": "2026-04-28-我迷失在了黑夜里",
      "dataPath": "post-data/2026-04-28-%E6%88%91%E8%BF%B7%E5%A4%B1%E5%9C%A8%E4%BA%86%E9%BB%91%E5%A4%9C%E9%87%8C.json",
      "source": "post",
      "kind": "videos",
      "title": "我迷失在了黑夜里",
      "publishedIndex": 22,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": {
        "src": "https://github.com/qqqzj-crane/qqqzj-crane-blog-assets/releases/download/assets-draft-draft-2026-04-28-moiqov4f-98a1b42d/inthedark.jpg",
        "alt": "inthedark"
      },
      "excerpt": "::: note Warning！！！ 观前提醒： 本文仅为脸滚键盘的随意组合，请勿与本人联系在一起。 ::: “我祈祷拥有一颗透明的心灵，和会流泪的眼睛。” 可是，“会流泪的眼睛” 没有用，哭 解决不了任何问题，就好像今天的杭州又下起了雨...",
      "readingMinutes": 1,
      "createdAt": "2026-04-28T00:00:00.000Z"
    },
    {
      "id": "life/2026-05-03-到家前的一刻.md",
      "slug": "2026-05-03-到家前的一刻",
      "dataPath": "post-data/2026-05-03-%E5%88%B0%E5%AE%B6%E5%89%8D%E7%9A%84%E4%B8%80%E5%88%BB.json",
      "source": "post",
      "kind": "videos",
      "title": "到家前的一刻",
      "publishedIndex": 28,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "qqqzj-crane",
      "url": "",
      "previewImage": null,
      "excerpt": "回石狮 想来，也许久没有更新了。 这句话在凌晨的杭州东站里反复出现在我的脑海，像一条没有发出去的朋友圈文案。屏幕亮着，输入框空着，身边的人拖着行李箱从我面前经过，轮子压过地砖缝隙，发出细碎而规律的声响。凌晨的车站并不真正安静，只是所有声音都...",
      "readingMinutes": 4,
      "createdAt": "2026-05-03T00:00:00.000Z"
    }
  ]
};
