window.PUBLISHED_POSTS = {
  "growth": [
    {
      "id": "news/2026-04-25-homepage-reading-polish.md",
      "slug": "2026-04-25-homepage-reading-polish",
      "dataPath": "post-data/2026-04-25-homepage-reading-polish.json",
      "source": "post",
      "kind": "growth",
      "title": "首页和阅读体验继续打磨",
      "publishedIndex": 0,
      "stage": "Site Update",
      "tag": "建站",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "今天继续把 qqqzj@Crane 的首页和阅读体验往更顺手的方向调整了一版。重点不是增加大功能，而是处理那些一打开页面就能感受到的细节：位置、层级、宽度、字号和交互是否舒服。 首页更像入口了 首页现在会展示最近几篇文章，读者不用先在各个栏...",
      "readingMinutes": 2,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-25-site-update-roundup.md",
      "slug": "2026-04-25-site-update-roundup",
      "dataPath": "post-data/2026-04-25-site-update-roundup.json",
      "source": "post",
      "kind": "growth",
      "title": "网站阶段更新：从内容归档到阅读体验",
      "publishedIndex": 1,
      "stage": "Site Update",
      "tag": "建站",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "这两天 qqqzj@Crane 做了一轮比较密集的维护，已经不只是“能放文章”的第一版了。现在它更像一个可以长期写、长期查、长期扩展的个人学习档案。 这次主要更新有几块。 内容和发布方式 网站现在采用 private 源码仓库和 publi...",
      "readingMinutes": 2,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-24-first-news.md",
      "slug": "2026-04-24-first-news",
      "dataPath": "post-data/2026-04-24-first-news.json",
      "source": "post",
      "kind": "growth",
      "title": "完成个人网站第一版",
      "publishedIndex": 2,
      "stage": "Project 项目",
      "tag": "建站",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "今天借助 Codex 把 qqqzj@Crane 的第一版搭起来了，感谢 Chatgpt 呜呜呜。",
      "readingMinutes": 1,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-27-实现app.md",
      "slug": "2026-04-27-实现app",
      "dataPath": "post-data/2026-04-27-%E5%AE%9E%E7%8E%B0app.json",
      "source": "post",
      "kind": "growth",
      "title": "实现app",
      "publishedIndex": 13,
      "stage": "News 动态",
      "tag": "随笔",
      "author": "Trae645",
      "url": "",
      "previewImage": {
        "src": "media/news-2026-04-27-实现app/IMG_8988.jpg",
        "alt": "IMG_8988"
      },
      "excerpt": "ai王朝了我说",
      "readingMinutes": 1,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-27-site-app-performance-update.md",
      "slug": "2026-04-27-site-app-performance-update",
      "dataPath": "post-data/2026-04-27-site-app-performance-update.json",
      "source": "post",
      "kind": "growth",
      "title": "网站 App 化和阅读性能继续打磨",
      "publishedIndex": 14,
      "stage": "Site Update",
      "tag": "建站",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "这两天 qqqzj@Crane 又往前推了一截。对访客来说，它现在更像一个可以长期打开、长期阅读、长期回看的个人站：入口更清楚，页面更轻，文章和附件也更适合在手机和电脑上慢慢看。 这一轮更新主要集中在几个前台体验上。 域名和 App 化 主...",
      "readingMinutes": 2,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "news/2026-04-27-public-site-feature-guide.md",
      "slug": "2026-04-27-public-site-feature-guide",
      "dataPath": "post-data/2026-04-27-public-site-feature-guide.json",
      "source": "post",
      "kind": "growth",
      "title": "现在前台能用什么：一份访客功能说明",
      "publishedIndex": 15,
      "stage": "Site Guide",
      "tag": "建站",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "趁着这一轮更新刚收好，把 qqqzj@Crane 的前台也整理成一份说明。这里说的前台，就是普通访客打开 qqqzj.cn 后能直接看到、能直接使用的部分。 现在这个站点不只是文章列表，它更像一个小型个人档案馆：可以按时间看动态，按主题读笔...",
      "readingMinutes": 3,
      "createdAt": "2026-04-27T00:00:00.000Z"
    }
  ],
  "notes": [
    {
      "id": "notes/physics/2026-04-24-physics-lab-markdown-template.md",
      "slug": "2026-04-24-physics-lab-markdown-template",
      "dataPath": "post-data/2026-04-24-physics-lab-markdown-template.json",
      "source": "post",
      "kind": "notes",
      "title": "普物实验docx模版(❌)markdown(☑️)",
      "publishedIndex": 4,
      "stage": "Notes 笔记",
      "tag": "普物实验",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "我弄了这个 Markdown 模版，之后写普物实验报告就不用再被 docx 格式卡住了。 文件放在这里，直接下载就能用。 下载实验报告 Markdown 模版 下载预习报告 Markdown 模版 下载配套 CSS 样式",
      "readingMinutes": 1,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-24-mathematical-analysis-i.md",
      "slug": "2026-04-24-mathematical-analysis-i",
      "dataPath": "post-data/2026-04-24-mathematical-analysis-i.json",
      "source": "post",
      "kind": "notes",
      "title": "数学分析 I",
      "publishedIndex": 5,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "实数、确界与函数 实数集的基本性质 实数集 $\\mathbb R$ 的常用性质： 1. 有序性：任意 $a,b\\in\\mathbb R$ 可比较大小。 2. 传递性：若 $ab$，$bc$，则 $ac$。 3. 阿基米德性：若 $a0$，$...",
      "readingMinutes": 22,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-24-mathematical-analysis-i-review-outline.md",
      "slug": "2026-04-24-mathematical-analysis-i-review-outline",
      "dataPath": "post-data/2026-04-24-mathematical-analysis-i-review-outline.json",
      "source": "post",
      "kind": "notes",
      "title": "数学分析 I 复习提纲",
      "publishedIndex": 6,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "来源：数分I复习.pdf。 参考校订：数学分析 上.pdf、《数学分析》辅导.pdf。 本文件按复习页内容整理为考前提纲，公式已按标准表述校正。 1. 实数完备性与确界 确界原理 非空有上界数集必有上确界；非空有下界数集必有下确界。 等价完...",
      "readingMinutes": 5,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/math/2026-04-24-linear-algebra-i.md",
      "slug": "2026-04-24-linear-algebra-i",
      "dataPath": "post-data/2026-04-24-linear-algebra-i.json",
      "source": "post",
      "kind": "notes",
      "title": "线性代数 I",
      "publishedIndex": 7,
      "stage": "Notes 笔记",
      "tag": "数学",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "线性方程组与行简化阶梯形 行简化阶梯形 行简化阶梯矩阵满足： 1. 零行在非零行下方； 2. 每个非零行首个非零元为 $1$； 3. 主元所在列其余元素全为 $0$； 4. 主元位置从上到下向右移动。 线性方程组化为简化阶梯形后： 出现 $...",
      "readingMinutes": 19,
      "createdAt": "2026-04-24T00:00:00.000Z"
    },
    {
      "id": "notes/physics/2026-04-25-physics-i-midterm-review-outline.md",
      "slug": "2026-04-25-physics-i-midterm-review-outline",
      "dataPath": "post-data/2026-04-25-physics-i-midterm-review-outline.json",
      "source": "post",
      "kind": "notes",
      "title": "普物 I 期中复习提纲（重点速览版）",
      "publishedIndex": 8,
      "stage": "Notes 笔记",
      "tag": "普物 I",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "General Physics I Midterm Review Outline / 普物 I 期中复习提纲 Based on / 依据：slides 课件、homework 作业、midterm 历年期中卷。 Focus / 重点：mec...",
      "readingMinutes": 9,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "notes/physics/2026-04-25-physics-i-midterm-mechanics-complete-review.md",
      "slug": "2026-04-25-physics-i-midterm-mechanics-complete-review",
      "dataPath": "post-data/2026-04-25-physics-i-midterm-mechanics-complete-review.json",
      "source": "post",
      "kind": "notes",
      "title": "普物 I 期中复习提纲（力学全覆盖版）",
      "publishedIndex": 9,
      "stage": "Notes 笔记",
      "tag": "普物 I",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "General Physics I Midterm Review Outline / 普物 I 期中复习提纲（Mechanics 讲义全覆盖版） Main reference / 主参考：普物I/reference books/mechan...",
      "readingMinutes": 14,
      "createdAt": "2026-04-25T00:00:00.000Z"
    }
  ],
  "videos": [
    {
      "id": "life/2026-04-24-04-travel-jinan&taishan.md",
      "slug": "2026-04-24-04-travel-jinan-taishan",
      "dataPath": "post-data/2026-04-24-04-travel-jinan-taishan.json",
      "source": "post",
      "kind": "videos",
      "title": "清明de济南与泰山",
      "publishedIndex": 3,
      "stage": "Project 项目",
      "tag": "旅游",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": {
        "src": "media/2026-04-24-travel-jinan-taishan/baotuquan.jpeg",
        "alt": "趵突泉"
      },
      "excerpt": "为了这次出行，清明前我真的付出了太多～～ 趵突泉 竟然只是三个冒水的洞？！ 夜里的泰山 泰山日出 “日上，正赤如丹，下有红光动摇承之”",
      "readingMinutes": 1,
      "createdAt": "2026-04-04T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-25-真好-又浪费了一天.md",
      "slug": "2026-04-25-真好-又浪费了一天",
      "dataPath": "post-data/2026-04-25-%E7%9C%9F%E5%A5%BD-%E5%8F%88%E6%B5%AA%E8%B4%B9%E4%BA%86%E4%B8%80%E5%A4%A9.json",
      "source": "post",
      "kind": "videos",
      "title": "真好，又浪费了一天",
      "publishedIndex": 10,
      "stage": "Life 生活",
      "tag": "日常",
      "author": "ZijunQiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "我真服了 今天的 Chatgpt 让我很恼火，今天的 General Physics 更是火上浇油 一边复习，一边对着电脑和他互动。不仅复习不成，功能也没给我正确实现（我已急哭） 好在最后也是成功优化了 UI 界面，不过下周三要考普物期中了...",
      "readingMinutes": 1,
      "createdAt": "2026-04-25T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-26-这个后端推送给我弄死了.md",
      "slug": "2026-04-26-这个后端推送给我弄死了",
      "dataPath": "post-data/2026-04-26-%E8%BF%99%E4%B8%AA%E5%90%8E%E7%AB%AF%E6%8E%A8%E9%80%81%E7%BB%99%E6%88%91%E5%BC%84%E6%AD%BB%E4%BA%86.json",
      "source": "post",
      "kind": "videos",
      "title": "这个后台推送给我弄死了",
      "publishedIndex": 11,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "zijunqiu-a",
      "url": "",
      "previewImage": null,
      "excerpt": "我真花了一早上 现在午饭还没吃 又玩了一早上AI 两点了还没吃",
      "readingMinutes": 1,
      "createdAt": "2026-04-26T00:00:00.000Z"
    },
    {
      "id": "notes/随笔/2026-04-26-qzj-老爹莅临检查.md",
      "slug": "2026-04-26-qzj-老爹莅临检查",
      "dataPath": "post-data/2026-04-26-qzj-%E8%80%81%E7%88%B9%E8%8E%85%E4%B8%B4%E6%A3%80%E6%9F%A5.json",
      "source": "post",
      "kind": "videos",
      "title": "qzj 老爹（并非）莅临检查",
      "publishedIndex": 12,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "junchao353-glitch",
      "url": "",
      "previewImage": {
        "src": "media/notes-随笔-2026-04-26-qzj-老爹莅临检查/IMG_8415.jpg",
        "alt": "ljc我是你爸爸"
      },
      "excerpt": "加油吧撑过这段时间就好了宝宝",
      "readingMinutes": 1,
      "createdAt": "2026-04-26T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-27-实验室好累.md",
      "slug": "2026-04-27-实验室好累",
      "dataPath": "post-data/2026-04-27-%E5%AE%9E%E9%AA%8C%E5%AE%A4%E5%A5%BD%E7%B4%AF.json",
      "source": "post",
      "kind": "videos",
      "title": "实验室好累",
      "publishedIndex": 16,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "Trae645",
      "url": "",
      "previewImage": {
        "src": "media/drafts/draft-2026-04-27-mogw92dy-d7548828/1ddc629b5dc3d09b77765b440753fbd8.png",
        "alt": "1ddc629b5dc3d09b77765b440753fbd8"
      },
      "excerpt": "严肃品鉴unitree代码中",
      "readingMinutes": 1,
      "createdAt": "2026-04-27T00:00:00.000Z"
    },
    {
      "id": "life/2026-04-27-我最近好像有点幸福了.md",
      "slug": "2026-04-27-我最近好像有点幸福了",
      "dataPath": "post-data/2026-04-27-%E6%88%91%E6%9C%80%E8%BF%91%E5%A5%BD%E5%83%8F%E6%9C%89%E7%82%B9%E5%B9%B8%E7%A6%8F%E4%BA%86.json",
      "source": "post",
      "kind": "videos",
      "title": "我最近好像有点幸福了",
      "publishedIndex": 17,
      "stage": "Life Log 生活记录",
      "tag": "随笔",
      "author": "junchao353-glitch",
      "url": "",
      "previewImage": null,
      "excerpt": "我好像天快晴了",
      "readingMinutes": 1,
      "createdAt": "2026-04-27T00:00:00.000Z"
    }
  ]
};
